import Head from 'next/head'
import Carousel from '@/modules/productCard'
import { useEffect, useState } from 'react';

export default function Home() {

  const items = [
    { productName: 'IronMaxx 100% Whey Protein', productPrice: 31.99, protein: true, weight: 9, salePrice: 27.99, productPicture: 'im_900_bn.png', variants: [], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(235,255,103,1) 0%, rgba(49,168,222,1) 50%, rgba(235,255,103,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow'},
    { productName: 'Skull Labs 100% Iso Whey', productPrice: 64.99, protein: true, weight:20, productPicture: 'sl_iw.png', variants: [/* ... */], backgroundColor: 'red', 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(65,170,85,1) 0%, rgba(0,0,0,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'blue' },
    { productName: 'Kevin Levrone Anabolic Iso Whey Protein', productPrice: 70.00, protein: true, weight: 20, text:"ass", productPicture: 'kl_iso_2000.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(255,253,166,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'Kevin Levrone Gold Whey', productPrice: 55.00, protein: true, weight: 20, productPicture: 'kl_gw.png', variants: [/* ... */], 
    titleBackgroundColor: '#cfb97c;', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'Optimum Nutrition 100% Gold Standard Whey', productPrice: 34.99, protein: true, weight: 9, productPicture: 'on_wg_900.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(255,65,65,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'Extrifit Instant Whey', productPrice: 63.99, protein: true, weight: 20, productPicture: 'ef_w.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(255,132,77,1) 0%, rgba(255,203,58,1) 20%, rgba(255,123,26,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'BADASS Whey', productPrice: 55.00, protein: true, weight: 20, productPicture: 'ba_w.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(244,2,2,1) 0%, rgba(0,0,0,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'ActivLab Muscle Up', productPrice: 16.00, protein: true, weight: 7, productPicture: 'al_mu.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(255,39,39,1) 30%, rgba(255,39,39,1) 60%, rgba(255,255,255,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'ActivLab Mega Protein', productPrice: 16.00, protein: true, weight: 7, productPicture: 'al_mp_700g.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(255,39,39,1) 30%, rgba(255,39,39,1) 60%, rgba(255,255,255,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },
    { productName: 'Myprotein Impact Whey Protein', productPrice: 26.99, protein: true, weight: 10, productPicture: 'mp_iw_1000.png', variants: [/* ... */], 
    titleBackgroundColor: 'linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(18,185,190,1) 30%, rgba(18,185,190,1) 60%, rgba(136,136,136,1) 100%);', priceBackgroundColor: 'blue', fontColor: 'yellow' },



    // Add more items as needed
  ];
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <Carousel items={items} time={5000}/>
      </div>
    </>
  )
}